### ISSUE TITLE
User is different than author in some cases

### ISSUE THREAD

**Issue by brunocasanova** [findhit/snitcher#5]
Internally we have a problem with this function: https://github.com/findhit/snitcher/blob/master/lib/reporter/github/index.js#L152-L183 with the `options`.

In this case the `options.user` its different than the `options.author` while searching for an existing issue and because of that, snitcher isn't group/commenting in the existing issue and instead, its creating another issue because its assuming that the `options.user` its equal the `options.author` and give no result in the search and it's not bypassing this condition: https://github.com/findhit/snitcher/blob/master/lib/reporter/github/index.js#L171 that let snitcher creates the comment.

I'm going to create a PR with a possible solution for that.

**Comment by cusspvz** [comment]
Fix included on `0.1.1` patch released version.
